### ISSUE TITLE
Classname not printed

### ISSUE THREAD

**Issue by apheleia** [FriendsOfPHP/Sami#147]
When I run `php sami.phar parse config.php`, the errors do not show the classname (also for `update`, of course). The output is:
```bash
ERROR: An error occurred while parsing "::__construct" line "37": "2" @param tags are expected but only "1" found
```
And I don't want to look through *all* my constructors :)

config.php:
```php
<?php

return new Sami\Sami('../git-repository/src');
```

**Comment by aik099** [comment]
1. Does this happen only for constructor or other methods as well?
2. Any PR coming in?

**Comment by apheleia** [comment]
All methods. What do you mean, if a PR is cimong in?

**Comment by apheleia** [comment]
I could try and fix it tonight, but right now I am at work.

**Comment by aik099** [comment]
> What do you mean, if a PR is coming in?

From my experience people reporting issues usually are willing to submit PR, because the issue being reported is one discovered at work and is usually a blocker to them.

Some people just report issues and don't send PR. By asking I've made visible so that an issue is open for any willing person to implement or we should wait for issue author to send PR as well.

**Comment by apheleia** [comment]
I will look at it tonight and fix it if possible. Will get back.
