### ISSUE TITLE
Bin file not created correctly

### ISSUE THREAD

**Issue by Petah** [FriendsOfPHP/Sami#154]
When installing globally via composer the bin file is not created correctly. It creates a `sami.php` file and a `sami.php.bat` file. Running `sami.php.bat` works fine, running `sami.php` opens the file in a text editor, and running `sami` does nothing.

**Comment by aik099** [comment]
> Running sami.php.bat works fine

There is no `sami.php.bat` file in repository.

> running sami.php opens the file in a text editor

I guess that's default behavior for PHP files on Windows. You should run `php sami.php`.

> and running sami does nothing.

There is no such `sami` file.

**Comment by Petah** [comment]
`php sami.php` does: `Could not open input file: sami.php`

If this in intentional behaviour I apologize, it is just uncommon and inconvenient to have to run `sami.php.bat`

**Comment by aik099** [comment]
Then maybe we should rename `sami.php` to `sami` and then:
* on Linux `sami` command would work
* on Windows: `sami.bat` command would work

**Comment by brunoaugusto** [comment]
Just a side note, even for future reference, who knows, at least on Windows, PHP executable path must be present on `PATH` Environment Variable in order to be called simply as `php` -AND- the Windows Prompt (PowerShell, GIT Bash...) must be pointing to the same directory where `sami.php` is located to be used like this, without specifying the full path to it

For example, all my development binaries are located in `D:\bin`, with or without sub-directories, depending the case for convenience. If I go there through Windows Explorer, open the Prompt (I modified my REGEDIT to have a context option for that in every folder) and run `php -f sami.php` it *should* work ("should" because I use the PHAR version).

But if I'm lazy and just go with <kbd>Win</kbd> + <kbd>R</kbd> and type *cmd*, case in which the prompt would be pointing by default to `C:\Users\Bruno` I would have to run SAMI as `php -f "D:\bin\sami.php"`

**Comment by smith86n** [comment]
I go to word pad

**Comment by smith86n** [comment]
---------- Forwarded message ----------
From: n smith <smith86n@gmail.com>
Date: Tue, Oct 10, 2017 at 8:07 PM
Subject: Re: Our fellow Americans need our help:
To: democraticparty@democrats.org


you are a shadow

**Comment by brunoaugusto** [comment]
That's not the place to spam politically inclined messages
