### ISSUE TITLE
Error in parsing functions arguments

### ISSUE THREAD

**Issue by GabMar** [FriendsOfPHP/Sami#194]
Sami does not render the right namespace for the parameters declared in a functions.
For example: 
```php
use nam1\nam2\Bar;

/**
 * @param Bar $bar
 */
public function foo(Bar $bar)
{
    ....
}
```
With this syntax Sami doesn't manage to identify the right namespace for the Bar object.
The only way to get the right documentation is to delete the declaration inside the function:
```php
use nam1\nam2\Bar;

/**
 * @param Bar $bar
 */
public function foo($bar)
{
    ....
}
```

**Comment by oniric85** [comment]
I dig into this issue a bit, the problem seems to origin from the `NodeVisitor::resolveAlias` method which is returning the supposedly correct full namespace of a type. That function checks whether or not the `$type` starts with a `\`; if that's not the case Sami appends the class name of the class in the current context. That would work if `$type` followed this constraint but the type string is created from an explicit type casting `(string) $params->type`, which, from my research, calls the corresponding `__toString` method on `PhpParser\Node\Name\FullyQualified` of (PhpParser library) which does not seems to add a `\` in front of the returned value (see https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Name.php#L96-L104).

I don't know exactly the inner workings of Sami so I could be wrong but I feel like we could use the PhpParser object to determine if the name is FQDN or not.

**Comment by aik099** [comment]
The `PhpParser\Node\Name\FullyQualified` is always returning FQCN that doesn't start with `\` because PHP reflection does the same.

But the Symfony documentation is generated using Sami. I'm sure in there there are cases, when class name from another namespace is specified in both DocBlock and typehint.

**Comment by oniric85** [comment]
@aik099 sure there are cases and that is actually making me think that perhaps it is generated with a different version of Sami (not the most recent one maybe). I was able to produce two simple PHP classes and a Sami configuration which reproduces the problem, here is the gist https://gist.github.com/oniric85/09d4c028c991a8e4b3f0

I'm also attaching a screenshot which shows the problem:
![poc](https://cloud.githubusercontent.com/assets/3330275/11757522/5058adba-a062-11e5-8324-b9d807c140e9.png)

As you can see the tooltip on the param documentation has the wrong namespace associated. I'm using Sami 3.1.0 if this can help.

**Comment by oniric85** [comment]
I just found out that Laravel is using Sami too for documentation and the problem shows up in their doc like here http://laravel.com/api/5.0/Illuminate/Session/DatabaseSessionHandler.html you can see ConnectionInterface is not clickable and the tooltip on it has the wrong namespace.

**Comment by aik099** [comment]
Is it happening in 1.x or 2.x versions of Sami?

**Comment by oniric85** [comment]
I've tried version 2.0.0 and it works correctly (link is created pointing to the correct class), tried version 3.0.0 and I get the problem. If it can be useful 2.0.0 came with php-parser 0.9.5 while 3.0.0 came with php-parser 1.4.1.

**Comment by shulard** [comment]
Hello, is there someone working on it ?

**Comment by fabpot** [comment]
@shulard As far as I know, nobody is working on this one. Any help would be much appreciated.
