### ISSUE TITLE
Generated documentation is missing param and return documentation

### ISSUE THREAD

**Issue by abayob** [FriendsOfPHP/Sami#267]
Hey hey,

I am currently generating documentation for my project. 
It is a average sized CMS with about 300 classes.
When I started to use the documentation, I noticed some things are missing, but I can't figure out WHY?

For example the mysql-adapter.php class misses documentation for some functions:
-  changeTable() -> no return documentation and missing param type and description
- prepare() -> no return doc and the params miss the type and description docs
- Same for execute(), insert() and insertMultiple().

I added the PHP class, the generated HTML page and the used Sami config file in this zip file: [Sami-doc.zip](https://github.com/FriendsOfPHP/Sami/files/729687/Sami-doc.zip).
I am using the phar file version (downloaded 2 days ago from this github page) and PHP5.6 to generate the documentation.

Am I doing something wrong?

EDIT:
I also tested this with an older Sami version: http://get.sensiolabs.org/sami-v3.3.0.phar, but the result is still the same...

**Comment by net-tools** [comment]
Hi,

Maybe I have found what is wrong in your code (as I had a similar issue some months ago).

I noticed that all methods not documented (prepare, execute, insert, etc.) have multiple spaces or tabs in the phpdoc to align things nicely between @param, the type, the var name, and the description. changeTable or getTable don't have padding spaces to align content, so it's working. You have to remove such padding (I don't pad lines in my php files and I never had an issue like that one).

Then I had a look at he missing type and description and noticed that all these methods don't have the right amount of padding at the line beginning. addSortOrder has 4 spaces before and it's doc output is good. Other methods have 1 tab or 3 spaces.

Since [Markdown](http://daringfireball.net/projects/markdown/syntax) formatting is used for phpdoc, it's rules may also apply here (see link before and scroll to "code blocks" section).

I don't have time to take your file and test on my host, but I'm pretty sure this is related to spaces/padding.

Please provide feedback if I was right !

**Comment by abayob** [comment]
Thank you very much net-tools, that fixed the issue!
