### ISSUE TITLE
PHPUnit 6 conflict

### ISSUE THREAD

**Issue by bretterer** [FriendsOfPHP/Sami#288]
It seems that PHPUnit 6 requires phpdocumentor/reflection-docblock > 3.0.  This causes sami to not be able to be installed because it requires ~2.0

Can you update the requirement here so we can use phpunit 6+ AND Sami?

**Comment by hswong3i** [comment]
Use https://github.com/consolidation/cgr instead?

**Comment by bretterer** [comment]
Error Log

```
composer require sami/sami
Using version ^4.0 for sami/sami
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install sami/sami v4.0.6
    - Conclusion: don't install sami/sami v4.0.5
    - Conclusion: don't install sami/sami v4.0.4
    - Conclusion: don't install sami/sami v4.0.3
    - Conclusion: don't install sami/sami v4.0.2
    - Conclusion: don't install sami/sami v4.0.1
    - Conclusion: remove phpdocumentor/reflection-docblock 3.1.1
    - Installation request for sami/sami ^4.0 -> satisfiable by sami/sami[v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6].
    - Conclusion: don't install phpdocumentor/reflection-docblock 3.1.1
    - sami/sami v4.0.0 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.0, 3.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.1, 3.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.2, 3.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.3, 3.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.4, 3.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.5, 3.1.1].
    - Installation request for phpdocumentor/reflection-docblock (locked at 3.1.1) -> satisfiable by phpdocumentor/reflection-docblock[3.1.1].
```

**Comment by hswong3i** [comment]
This is because both sami and phpunit are dev tools but not libraries, so they don't really care if they conflict with any other else (i.e. they seems themselves as top-level project for install individually). 

That's why if you install both "under" your working copy with require/require-dev, as they don't care each other, they will generate dependency conflict for you.

So my suggestion:

- DON'T require/require-dev dev tools "under" your working copy, if you are not using them "within" you core logic, but just use it "after" coding (e.g. use phpunit for test, use sami for doc generate)
- DO install such dev tools as global packages , so you could use them for all of your R&D projects

BTW, since those dev tools will STILL have dependency conflict with each other even install as global packages, so using `cgr` to install them under different directories will simply solve the problem ;-)

You may have a look with my project for more idea:

- https://github.com/authbucket/oauth2-php/blob/master/.travis.yml
- https://github.com/authbucket/oauth2-php/blob/master/composer.json

**Comment by fabpot** [comment]
See 6c89fec. Sami should not be installed as a Composer dependency.

**Comment by bretterer** [comment]
@fabpot still has issues if installing other things as global.   ie.  I have a requirement for a project to use phpdocumentor, which is installed globally.  It prevents me from being able to install sami globally as well.
