### ISSUE TITLE
Implement @internal tag

### ISSUE THREAD

**Issue by rightfold** [FriendsOfPHP/Sami#99]
Is it possible to document something as being internal to my library? phpDocumentor supports [`@internal`](http://www.phpdoc.org/docs/latest/for-users/phpdoc/tags/internal.html) for this.

[`@ignore`](http://www.phpdoc.org/docs/latest/for-users/phpdoc/tags/ignore.html) would also be nice.

**Comment by aik099** [comment]
@ezzatron , do you have a repository + sami config where you got that error?

**Comment by erikwiffin** [comment]
In `Sami/Parser/NodeVisitor.php` for all three filtered add methods, the filter is called before the docblock is parsed. It's an easy fix, but it means a lot more processing happens to classes/methods/properties that will eventually be filtered out. I can amend my open pull request with the obvious fix, or make a new one, if you'd like.

**Comment by aik099** [comment]
@erikwiffin , better to create new one. Now all code before `$this->context->enterClass($class);` call (which actually does DocBlock parsing) will be called before filtering I guess.

This might be a bad thing because you can see that DocBlock parsing errors are set to context, but if we never set class itself in the context, then what happens with these errors. Maybe we should keep these errors in `$errors` variable and then set it to context only when we know, that class isn't filtered out.
